# Generated by Django 2.2 on 2021-01-11 23:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page_navigation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmiralSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='')),
                ('caption', models.CharField(default='admiral suite', max_length=225)),
                ('heading', models.CharField(max_length=225)),
                ('sqm', models.PositiveSmallIntegerField(verbose_name='sqm')),
                ('description', models.TextField(max_length=800)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section Admiral Suite',
                'verbose_name_plural': 'Admiral Suites',
            },
        ),
        migrations.CreateModel(
            name='BodyFullChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=225)),
                ('sailing_area', models.CharField(max_length=225)),
                ('minimum_nights', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CharterRatesInclude',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charter_rate_includes', to='page_navigation.Page')),
            ],
            options={
                'verbose_name': 'Section Charter Rates Include',
                'verbose_name_plural': 'Charter Rates Include',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommodoreSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='')),
                ('caption', models.CharField(default='commodore suite', max_length=225)),
                ('heading', models.CharField(max_length=225)),
                ('sqm', models.PositiveSmallIntegerField(verbose_name='sqm')),
                ('description', models.TextField(max_length=800)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section Commodore Suite',
                'verbose_name_plural': 'Commodore Suites',
            },
        ),
        migrations.CreateModel(
            name='DeckTechnical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=225)),
                ('description', models.TextField(max_length=800)),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section Deck Technical',
                'verbose_name_plural': 'Deck Technical',
            },
        ),
        migrations.CreateModel(
            name='DeluxeStateroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(default='deluxe staterooms', max_length=225)),
                ('heading', models.CharField(max_length=225)),
                ('sqm', models.PositiveSmallIntegerField(verbose_name='sqm')),
                ('description', models.TextField(max_length=800)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section Deluxe Stateroom',
                'verbose_name_plural': 'Deluxe Staterooms',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('heading', models.CharField(blank=True, max_length=225)),
                ('description', models.TextField(blank=True, max_length=800)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations', to='page_navigation.Page')),
            ],
            options={
                'verbose_name': 'Section Destination',
                'verbose_name_plural': 'Destination',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(default='Dining', max_length=225)),
                ('heading', models.CharField(max_length=225)),
                ('description', models.TextField(max_length=800)),
                ('image', models.ImageField(upload_to='')),
                ('to', models.CharField(default='/contact-us', help_text='button link', max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section Dining',
                'verbose_name_plural': 'Dining',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=225)),
                ('heading', models.CharField(max_length=225)),
                ('description', models.TextField(max_length=800)),
                ('reverse', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilities', to='page_navigation.Page')),
            ],
            options={
                'verbose_name': 'Section Facility',
                'verbose_name_plural': 'Facilities',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section Hero',
                'verbose_name_plural': 'Heroes',
            },
        ),
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=225)),
                ('access_token', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name': 'Section Instagram',
                'verbose_name_plural': 'Instagram Token',
            },
        ),
        migrations.CreateModel(
            name='InstagramTestimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=225)),
                ('link', models.URLField(blank=True, max_length=225)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instagram',
                'verbose_name_plural': 'Instagram',
            },
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('heading', models.CharField(blank=True, max_length=225)),
                ('description', models.TextField(blank=True, max_length=800)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('youtube_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section Intro',
                'verbose_name_plural': 'Intro',
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(default='itineraries', max_length=225)),
                ('image', models.ImageField(upload_to='')),
                ('heading', models.CharField(max_length=225)),
                ('description', models.TextField(max_length=800)),
                ('to', models.CharField(default='/rates-and-schedule', help_text='button link', max_length=225)),
            ],
            options={
                'verbose_name': 'Section Itinerary',
                'verbose_name_plural': 'Itineraries',
            },
        ),
        migrations.CreateModel(
            name='Occasions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(default='Occasions', max_length=225)),
                ('heading', models.CharField(max_length=225)),
                ('description', models.TextField(max_length=800)),
                ('image', models.ImageField(upload_to='')),
                ('to', models.CharField(default='/contact-us', help_text='button link', max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section Occasions',
                'verbose_name_plural': 'Occasions',
            },
        ),
        migrations.CreateModel(
            name='SuitesAndStateroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=225)),
                ('to', models.CharField(default='/suites-and-staterooms', max_length=225)),
            ],
            options={
                'verbose_name': 'Section Suites And Staterooms',
                'verbose_name_plural': 'Suites And Staterooms',
            },
        ),
        migrations.CreateModel(
            name='Sustainability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=225)),
                ('description', models.TextField(max_length=800)),
                ('image', models.ImageField(upload_to='')),
                ('to', models.CharField(default='/contact-us', help_text='button link', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section Sustainability',
                'verbose_name_plural': 'Sustainability',
            },
        ),
        migrations.CreateModel(
            name='TableFullChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_capacity', models.CharField(blank=True, max_length=225)),
                ('extra_guest', models.TextField(blank=True, max_length=800)),
                ('relocation_fee', models.CharField(blank=True, max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section Table Full Chapter',
                'verbose_name_plural': 'Table Full Chapters',
            },
        ),
        migrations.CreateModel(
            name='TableSpesification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section Table Spesification',
                'verbose_name_plural': 'Table Spesifications',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='TheVessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(default='The Vessel', max_length=225)),
                ('heading', models.CharField(max_length=225)),
                ('description', models.TextField(blank=True, max_length=800)),
                ('image', models.ImageField(upload_to='')),
                ('to', models.CharField(default='/the-vessel', help_text='button link', max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section The Vessel',
                'verbose_name_plural': 'The Vessel',
            },
        ),
        migrations.CreateModel(
            name='Voyages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Voyages', max_length=225)),
                ('description', models.TextField(blank=True, max_length=800)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section Voyages',
                'verbose_name_plural': 'Voyages',
            },
        ),
        migrations.CreateModel(
            name='VoyagesItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('heading', models.CharField(max_length=225)),
                ('description', models.TextField(max_length=800)),
                ('to', models.CharField(help_text='button link', max_length=225)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages_items', to='page_navigation.Page')),
            ],
            options={
                'verbose_name': 'Section Voyages Item',
                'verbose_name_plural': 'Voyages Items',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('src', models.FileField(upload_to='')),
                ('type', models.CharField(help_text='example: video/mp4', max_length=20)),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='section.Hero')),
            ],
        ),
        migrations.CreateModel(
            name='TheDecks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caption', models.CharField(default='The Decks', max_length=100)),
                ('heading', models.CharField(max_length=225)),
                ('description', models.TextField(max_length=800)),
                ('image', models.ImageField(upload_to='')),
                ('to', models.CharField(default='/the-vessel/specification', help_text='button link', max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_decks', to='page_navigation.Page')),
            ],
            options={
                'verbose_name': 'Section The Decks',
                'verbose_name_plural': 'The Decks',
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('image', models.ImageField(upload_to='')),
                ('comment', models.TextField(max_length=800)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instagram', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='testimony', to='section.InstagramTestimony')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to='page_navigation.Page')),
            ],
            options={
                'verbose_name': 'Section Testimony',
                'verbose_name_plural': 'Testimonies',
            },
        ),
        migrations.CreateModel(
            name='Tabs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=225)),
                ('description', models.TextField(max_length=800)),
                ('image', models.ImageField(upload_to='')),
                ('to', models.CharField(default='/voyages', help_text='button link', max_length=225)),
                ('voyages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs_data', to='section.Voyages')),
            ],
            options={
                'verbose_name': 'Tab',
                'verbose_name_plural': 'Tabs',
            },
        ),
        migrations.CreateModel(
            name='Personil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('image', models.ImageField(upload_to='')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data', to='section.Team')),
            ],
            options={
                'verbose_name': 'Section Personil',
                'verbose_name_plural': 'Personil',
            },
        ),
        migrations.CreateModel(
            name='PerNight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True)),
                ('body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates_per_night', to='section.BodyFullChapter')),
            ],
        ),
        migrations.CreateModel(
            name='MenuSuitesroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admiral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='section.AdmiralSuite')),
                ('commodore', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='section.CommodoreSuite')),
                ('deluxe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='section.DeluxeStateroom')),
                ('suites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='section.SuitesAndStateroom')),
            ],
        ),
        migrations.CreateModel(
            name='IconDeluxeStateroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='')),
                ('deluxe_stateroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='section.DeluxeStateroom')),
            ],
            options={
                'verbose_name': 'Icon',
                'verbose_name_plural': 'Icons',
            },
        ),
        migrations.CreateModel(
            name='HeaderSpesification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=225)),
                ('value', models.CharField(max_length=225)),
                ('align', models.CharField(choices=[('start', 'Start'), ('center', 'Center'), ('end', 'End')], default='start', max_length=6)),
                ('table_spesification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='section.TableSpesification')),
            ],
        ),
        migrations.CreateModel(
            name='HeaderFullChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=225)),
                ('value', models.CharField(max_length=225)),
                ('align', models.CharField(choices=[('start', 'Start'), ('center', 'Center'), ('end', 'End')], default='start', max_length=6)),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('table_full_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='section.TableFullChapter')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryDeluxeStateroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('deluxe_stateroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='section.DeluxeStateroom')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.CreateModel(
            name='GalleryCommodoreSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('commodore_suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='section.CommodoreSuite')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.CreateModel(
            name='GalleryAdmiralSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('admiral_suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='section.AdmiralSuite')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.CreateModel(
            name='FacilityGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery', to='section.Facility')),
            ],
            options={
                'verbose_name': 'Facility Gallery',
                'verbose_name_plural': 'Facility Galleries',
            },
        ),
        migrations.CreateModel(
            name='DestinationGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery', to='section.Destination')),
            ],
            options={
                'verbose_name': 'Destination Gallery',
                'verbose_name_plural': 'Destination Galleries',
            },
        ),
        migrations.CreateModel(
            name='DeckPreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField(max_length=800)),
                ('image', models.FileField(upload_to='')),
                ('mobile_image', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deck_previews', to='page_navigation.Page')),
            ],
            options={
                'verbose_name': 'Section Deck Preview',
                'verbose_name_plural': 'Deck Previews',
            },
        ),
        migrations.CreateModel(
            name='DataCharterInclude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=800)),
                ('charter_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data', to='section.CharterRatesInclude')),
            ],
            options={
                'verbose_name': 'Data Charter Include',
                'verbose_name_plural': 'Data Charter Includes',
            },
        ),
        migrations.CreateModel(
            name='BodySpesification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('value', models.TextField(max_length=500)),
                ('table_spesification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='section.TableSpesification')),
            ],
        ),
        migrations.AddField(
            model_name='bodyfullchapter',
            name='table_full_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='section.TableFullChapter'),
        ),
    ]
