# Generated by Django 2.2 on 2021-01-17 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabs',
            options={'ordering': ['id'], 'verbose_name': 'Tab', 'verbose_name_plural': 'Tabs'},
        ),
    ]
