# Generated by Django 2.2 on 2021-01-11 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section', '0001_initial'),
        ('page_navigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='admiral_suite',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='section.AdmiralSuite', verbose_name='Section Admiral Suite'),
        ),
        migrations.AddField(
            model_name='page',
            name='commodore_suite',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='section.CommodoreSuite', verbose_name='Section Commodore Suite'),
        ),
        migrations.AddField(
            model_name='page',
            name='deck_technical',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='section.DeckTechnical', verbose_name='Section Deck Technical'),
        ),
        migrations.AddField(
            model_name='page',
            name='deluxe_stateroom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='section.DeluxeStateroom', verbose_name='Section Deluxe Stateroom'),
        ),
        migrations.AddField(
            model_name='page',
            name='dining',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='section.Dining', verbose_name='Section Dining'),
        ),
        migrations.AddField(
            model_name='page',
            name='hero',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='section.Hero', verbose_name='Section Hero'),
        ),
        migrations.AddField(
            model_name='page',
            name='instagram',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='section.Instagram', verbose_name='Section Instagram'),
        ),
        migrations.AddField(
            model_name='page',
            name='intro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='section.Intro', verbose_name='Section Intro'),
        ),
        migrations.AddField(
            model_name='page',
            name='itinerary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='section.Itinerary', verbose_name='Section Itinerary'),
        ),
        migrations.AddField(
            model_name='page',
            name='occasions',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='section.Occasions', verbose_name='Section Occasions'),
        ),
        migrations.AddField(
            model_name='page',
            name='suites_and_staterooms',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='section.SuitesAndStateroom', verbose_name='Section Suites And Staterooms'),
        ),
        migrations.AddField(
            model_name='page',
            name='sustainability',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='section.Sustainability', verbose_name='Section Sustainability'),
        ),
        migrations.AddField(
            model_name='page',
            name='table_full_chapter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='section.TableFullChapter', verbose_name='Section Table Full Chapter'),
        ),
        migrations.AddField(
            model_name='page',
            name='table_spesification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='section.TableSpesification', verbose_name='Section Table Spesification'),
        ),
        migrations.AddField(
            model_name='page',
            name='teams',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='section.Team', verbose_name='Section Team'),
        ),
        migrations.AddField(
            model_name='page',
            name='the_vessel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='section.TheVessel', verbose_name='Section The Vessel'),
        ),
        migrations.AddField(
            model_name='page',
            name='voyages',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='section.Voyages', verbose_name='Section Voyages'),
        ),
        migrations.AddField(
            model_name='menu',
            name='navigation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='page_navigation.Navigation'),
        ),
    ]
